global using System.ComponentModel.DataAnnotations;
global using Bookify.Data;
global using Bookify.Core.ViewModels;
global using Microsoft.EntityFrameworkCore;
global using AutoMapper;
global using Bookify.Core.Mapping;
global using Bookify.Core.Models;
global using Bookify.Filters;
global using Microsoft.AspNetCore.Mvc;